[global]
# Your Spotify account name.
username = "clay"

# Your Spotify account password.
password = "Sahil@2004spotify"
use_keyring = true
use_mpris = true
dbus_type = "session"
backend = "alsa" # use portaudio for macOS [homebrew]
device = "alsa_audio_device"  # omit for macOS
audio_format = "S16"
control = "alsa_audio_device"  # omit for macOS
mixer = "PCM"  # omit for macOS
volume_controller = "alsa"  # use softvol for macOS
on_song_change_hook = "command_to_run_on_playback_events"
device_name = "spotifyd"
bitrate = 320
cache_path = ""/Users/<your Username>/.cache/spotifyd"
max_cache_size = 1000000000
no_audio_cache = true
initial_volume = "90"
volume_normalisation = true
normalisation_pregain = -10
autoplay = true
zeroconf_port = 1234
proxy = "http://proxy.example.org:8080"
audio_dongle.
device_type = "computer"